<x-app-layout>
    <x-slot name="header">
        <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">Activity Details</h2>
            <a href="{{ route('activities.index') }}" class="bg-gray-100 hover:bg-gray-200 text-gray-700 font-semibold py-2.5 px-6 rounded-xl transition-all inline-flex items-center">
                <svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"/></svg>
                Back
            </a>
        </div>
    </x-slot>
    <div class="py-12"><div class="max-w-7xl mx-auto sm:px-6 lg:px-8 space-y-6">
    @if(session('success'))<div class="bg-gradient-to-r from-nss-green-50 to-nss-green-100 border-l-4 border-nss-green-500 text-nss-green-800 px-6 py-4 rounded-xl shadow-sm"><div class="flex items-center"><svg class="w-5 h-5 mr-3" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"/></svg>{{ session('success') }}</div></div>@endif
    <div class="bg-white/80 backdrop-blur-sm overflow-hidden shadow-xl sm:rounded-2xl border border-nss-green-100"><div class="p-8"><h3 class="text-lg font-bold text-gray-900 mb-6 flex items-center"><svg class="w-5 h-5 mr-2 text-nss-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>Activity Information</h3><dl class="grid grid-cols-1 gap-6"><div class="bg-gradient-to-r from-gray-50 to-white p-4 rounded-xl"><dt class="text-sm font-semibold text-gray-600">Title</dt><dd class="mt-2 text-base text-gray-900 font-medium">{{ $activity->title }}</dd></div><div class="bg-gradient-to-r from-gray-50 to-white p-4 rounded-xl"><dt class="text-sm font-semibold text-gray-600">Description</dt><dd class="mt-2 text-base text-gray-900">{{ $activity->description ?? 'N/A' }}</dd></div><div class="bg-gradient-to-r from-gray-50 to-white p-4 rounded-xl"><dt class="text-sm font-semibold text-gray-600">Created</dt><dd class="mt-2 text-base text-gray-900">{{ $activity->created_at->format('M d, Y h:i A') }}</dd></div></dl></div></div>
    <div class="bg-white/80 backdrop-blur-sm overflow-hidden shadow-xl sm:rounded-2xl border border-nss-green-100"><div class="p-8"><h3 class="text-lg font-bold text-gray-900 mb-6 flex items-center"><svg class="w-5 h-5 mr-2 text-nss-yellow-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"/></svg>Update Status</h3><form method="POST" action="{{ route('activities.updateStatus', $activity) }}" class="space-y-6">@csrf<div class="grid grid-cols-1 md:grid-cols-2 gap-6"><div><label for="status" class="block text-sm font-semibold text-gray-700 mb-2">Status</label><select name="status" id="status" required class="mt-1 block w-full rounded-xl border-gray-300 shadow-sm focus:border-nss-green-500 focus:ring-nss-green-500 transition-all"><option value="pending">⏳ Pending</option><option value="done">✅ Done</option></select></div><div><label for="remark" class="block text-sm font-semibold text-gray-700 mb-2">Remark <span class="text-gray-400 font-normal">(Optional)</span></label><input type="text" name="remark" id="remark" placeholder="Add a note..." class="mt-1 block w-full rounded-xl border-gray-300 shadow-sm focus:border-nss-green-500 focus:ring-nss-green-500 transition-all"></div></div><div class="pt-2"><button type="submit" class="bg-gradient-to-r from-nss-green-600 to-nss-green-700 hover:from-nss-green-700 hover:to-nss-green-800 text-white font-semibold py-2.5 px-6 rounded-xl shadow-md hover:shadow-lg transition-all duration-150">Update Status</button></div></form></div></div>
    <div class="bg-white/80 backdrop-blur-sm overflow-hidden shadow-xl sm:rounded-2xl border border-nss-green-100"><div class="p-8"><h3 class="text-lg font-bold text-gray-900 mb-6 flex items-center"><svg class="w-5 h-5 mr-2 text-nss-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>Update History</h3><div class="space-y-4">@forelse($activity->updates as $update)<div class="border-l-4 {{ $update->status === 'done' ? 'border-nss-green-500 bg-gradient-to-r from-nss-green-50 to-white' : 'border-nss-yellow-500 bg-gradient-to-r from-nss-yellow-50 to-white' }} pl-6 pr-4 py-4 rounded-r-xl shadow-sm hover:shadow-md transition-shadow"><div class="flex flex-col md:flex-row md:justify-between md:items-start gap-4"><div class="flex-1"><span class="px-3 py-1 text-xs font-semibold rounded-full {{ $update->status === 'done' ? 'bg-gradient-to-r from-nss-green-100 to-nss-green-200 text-nss-green-800 border border-nss-green-300' : 'bg-gradient-to-r from-nss-yellow-100 to-nss-yellow-200 text-nss-yellow-800 border border-nss-yellow-300' }} shadow-sm">{{ ucfirst($update->status) }}</span>@if($update->remark)<p class="mt-3 text-sm text-gray-700 bg-white/50 p-3 rounded-lg">{{ $update->remark }}</p>@endif</div><div class="text-left md:text-right text-sm"><div class="flex items-center md:justify-end mb-1"><div class="flex items-center justify-center w-7 h-7 rounded-full bg-gradient-to-br from-nss-green-500 to-nss-green-600 text-white font-semibold text-xs mr-2">{{ strtoupper(substr($update->user->name, 0, 1)) }}{{ strtoupper(substr(explode(' ', $update->user->name)[1] ?? $update->user->name, 0, 1)) }}</div><p class="font-semibold text-gray-900">{{ $update->user->name }}</p></div><p class="text-gray-600">{{ $update->created_at->format('M d, Y') }}</p><p class="text-nss-green-600 font-semibold">{{ $update->created_at->format('h:i A') }}</p></div></div></div>@empty<div class="text-center py-8"><svg class="w-12 h-12 text-gray-300 mx-auto mb-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/></svg><p class="text-gray-500">No updates recorded yet.</p></div>@endforelse</div></div></div>
    </div></div>
</x-app-layout>
